### ISSUE TITLE
Inactive Lovelace UI

### ISSUE THREAD

**Issue by onkytonk** [home-assistant/iOS#1801]
Straight out of the gate, I’m running iOS 15 public beta 3, so not sure if that’s the culprit or not. 

Basically when using the companion app, I can interact with the Lovelace ui, and the buttons, switches, etc respond in the ui, but nothing actually happens. Also, if the app is open, and I say turn on a light from a different device, it won’t update in the app. 
The app will only become responsive and update changes if I do a pull down to refresh. 

There is no such issues on Safari on the same iPhone. 

I’ve tried deleting and reinstalling the app with no luck. 

Also, I used to see “connection lost, reconnecting” upon reopening the app. This no longer happens. It’s still popping up in safari. 

Edit: just experienced the same issue on safari now. Companion app working fine on my iPad running iOS 14.

**Comment by mckochan** [comment]
This is also happening to me on iOS 15, but force quitting the app and re-opening solves the issue.  Need to do that once or twice a day now.

**Comment by tenallero** [comment]
The same for me.
Just after updating to iOS 15.
The Lovelace UI seems to be frozen. Buttons not responding, sensors not updating.
With iOS 14 all was running as expected.

**Comment by Stooovie** [comment]
Same. Starting to get like that even on desktop (Mac, Big Sur 11.6, Safari 14).

**Comment by tenallero** [comment]
If it helps ...
My configuration:

iOS 15.1 actually
The problem started just after installing iOS 15.0 beta.

Iphone 12 Pro Max
Home Assistant Companion 2021.8
Home Assistant core-2021.8.8

Browser_mod Release 1.3.0

My lovelace resource modules:

Homekit-panel-card/homekit-panel-card.js
light-popup-card/light-popup-card.js
cover-popup-card/cover-popup-card.js
switch-popup-card/switch-popup-card.js
custom-header/custom-header.js
swipe-card/swipe-card.js
lovelace-card-mod/card-mod.js
lovelace-card-tools/card-tools.js
mini-graph-card/mini-graph-card-bundle.js
light-entity-card/light-entity-card.js 
fan-control-entity-row/fan-control-entity-row.js
lovelace-slider-entity-row/slider-entity-row.js
config-template-card/config-template-card.js
vacuum-card/vacuum-card.js
webrtc/webrtc-camera.js
pvpc-hourly-pricing-card/pvpc-hourly-pricing-card.js
lovelace-fan-xiaomi/fan-xiaomi.js

**Comment by deluxestyle** [comment]
I'm having the same issue.
Here my config

iphone 11Pro, iOS 15.0.1
Home Assistant Companion 2021.8
Home Assistant core-2021.10.2

Browser_mod Release 1.5.0

My lovelace resource modules:
mini-media-player/mini-media-player-bundle.js
lovelace-fold-entity-row/fold-entity-row.js
vertical-stack-in-card/vertical-stack-in-card.js
lovelace-card-mod/card-mod.js
lovelace-card-tools/card-tools.js
lovelace-auto-entities/auto-entities.js
lovelace-swipe-navigation/swipe-navigation.js
lovelace-multiple-entity-row/multiple-entity-row.js
lovelace-paper-buttons-row/paper-buttons-row.js
vacuum-card/vacuum-card.js
scheduler-card/scheduler-card.js
lovelace-battery-entity-row/battery-entity-row.js
lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
button-card/button-card.js
lovelace-layout-card/layout-card.js
mini-graph-card/mini-graph-card-bundle.js
hass-hue-icons/hass-hue-icons.js
lovelace-template-entity-row/template-entity-row.js
lovelace-more-info-card/more-info-card.js

**Comment by johnwarne** [comment]
This started happening for me as well with the iOS 15 betas in July and has continued with the official releases.

**Comment by ideal2545** [comment]
Just checking in if this was looked at, I believe its affecting quite a bit of folks now...

**Comment by Stooovie** [comment]
Yes, no change as of 2021.11.1.

**Comment by Stooovie** [comment]
Also, no change with the official HA companion app for iOS. Issue is still present.

**Comment by gieljnssns** [comment]
Also everything up to date and issue still present.

**Comment by deluxestyle** [comment]
I have the feeling it is better now on my side. I disabled the background refresh on iOS level for the HA app and it seems that the app is connecting every time I open it.

**Comment by Stooovie** [comment]
> I have the feeling it is better now on my side. I disabled the background refresh on iOS level for the HA app and it seems that the app is connecting every time I open it.

You may be onto something. Man it's been almost a decade since I had issues with Background refresh!  I'll try for a day and report back. Thanks!

**Comment by ideal2545** [comment]
Man that seems so counter-intuitive but I'll give it a shot too because this is a painful bug on my end, its like every 10 minutes or less sometimes.

**Comment by deluxestyle** [comment]
It is also not the solution. I still have the issue from time to time. But it seems more responsive

**Comment by Stooovie** [comment]
Yes, same. It is better but not fixed 100 %

**Comment by michalk-k** [comment]
not sure where it have started. Noticing it for a month or so.
I'm on core 2021.9.7 upgraded from 2021.1.5. I'm not aware about this issue in 2021.1 the change might be related to other things like ios update or app update.
It happens on wifi (I suspected roaming) as well as LTE.

As mentioned, it seems that application doesn't refresh its state when needed. It remains responsive but doesn't communicate with HA.

Currently I'm using app v 2021.11, ios 15.0.1

**Comment by gieljnssns** [comment]
Can we try to solve this issue with the settings of safari on the iPhone? 
experimental WebKit settings?
But I don't know which to try. This are my settings. 
![82B9D0C0-5C6D-423E-8B3F-DE24B45908D9](https://user-images.githubusercontent.com/17234951/143488677-4616aeb0-dc0b-4d9a-90dc-977c5de6a963.png)
![A35F9E22-A70A-4007-9F01-1161D7D03D3F](https://user-images.githubusercontent.com/17234951/143488682-d0c702cd-4686-454d-b876-f6bba70b5b2f.png)
![F2999F5E-3313-4BC5-BDE7-607D4CF43E6D](https://user-images.githubusercontent.com/17234951/143488688-68188858-00d0-4866-b4f2-e584ad8c1f94.png)
![47E98363-CF66-4023-B346-6EF4CC342C1A](https://user-images.githubusercontent.com/17234951/143488693-922b3f95-dc7f-4722-b171-abed5a204e31.png)
![18E33B5B-5B58-4CBF-82B7-9F43A9B9C4AB](https://user-images.githubusercontent.com/17234951/143488696-86996dc1-9079-4bc6-87d5-a4386a39136b.png)
![0E2169D8-294B-4AB9-8CAA-D0622D428F9B](https://user-images.githubusercontent.com/17234951/143488699-f604cbeb-e477-4f25-b596-6fb00d948ae2.png)
![C63843DB-AC2D-42C8-B70A-5224DB24A4D7](https://user-images.githubusercontent.com/17234951/143488702-22109f1f-75a8-45f7-91eb-b673faf74a05.png)

**Comment by chendo** [comment]
I've had similar issues with other websocket reliant apps. I've found disabling "NSURLSession WebSocket" on Safari desktop helped with that, and have just done so for iPhone, but not sure if web views inside apps are affected by this setting.

**Comment by deluxestyle** [comment]
Any updates ? No one is looking into the issue? Anything we can provide?

**Comment by gieljnssns** [comment]
> I've had similar issues with other websocket reliant apps. I've found disabling "NSURLSession WebSocket" on Safari desktop helped with that, and have just done so for iPhone, but not sure if web views inside apps are affected by this setting.

I've tried this, but didn't help....

**Comment by gieljnssns** [comment]
Posting some links from -what I think- is the same issue
https://github.com/home-assistant/core/issues/57271
https://github.com/home-assistant/frontend/issues/10224
https://community.home-assistant.io/t/ios-15-beta-and-public-release-safari-companion-app-freezing/323755/14
https://community.home-assistant.io/t/gui-is-unresponsive-after-some-time-on-ios-before-page-refresh-pull-down-or-force-close-open-app-how-to-id-and-fix/340527
https://community.home-assistant.io/t/ios-app-eventually-stops-updating/339809

**Comment by Stooovie** [comment]
Yes, they are. I've been reporting this for three months now, and got zero response from developers.

**Comment by gieljnssns** [comment]
And this is a really annoying issue...

**Comment by mxilievski** [comment]
@zacwest can you please look at this and maybe tell us if this is a problem in the iOS app or is something that needs to be addressed in the frontend project?

**Comment by zacwest** [comment]
This is a frontend issue, but really an Apple bug that needs to be worked around. The root of the issue is that Safari/WKWebView in iOS 15 transitioned to a different WebSocket implementation which doesn't quickly pick up disconnections due to e.g. going in the background or some transient network issues, so the delay between data coming live again is the delay between the app coming to the foreground and the Safari/WKWebView detecting the WebSocket connection has ended. While the issue is happening, the WebSocket connection by all appearances is still connected, hence not getting the "offline" errors you normally would see.

We've brainstormed a few ways to try and work around this issue -- ping timeouts in the frontend, trying to replace the WebSocket implementation with the one that app uses for its own WebSocket connection -- but none of them are easy or straightforward workarounds.

**Comment by mxilievski** [comment]
@zacwest tnx a lot for answering.
Until we wait for a fix from Apple, is it possible to do some workaround like refreshing on each app open, this will always reconnect the websocket every single time no matter the socket connection state.

**Comment by zacwest** [comment]
It would also lose whatever content may be in the WebView. For example, if you're currently working on editing a template or something it would lose the content; this doesn't seem like a valid workaround. I've pinged the frontend folks to see if there's a way to reset just the WebSocket connection; if so, I can probably instruct that to happen since its disconnect/reconnect should be handled fine.

**Comment by zacwest** [comment]
I'd also love to corroborate: does iOS 15.2 (currently in beta) fix this issue for anyone? I haven't seen it recently and that's the major difference I can think of.

**Comment by tenallero** [comment]
@zacwest 
Thanks for answering

**Comment by Stooovie** [comment]
@zacwest thanks Zac! I'm happy to finally get an answer from a dev as it looked it could be an user error, DNS misconfiguration, anything really. God knows Apple doesn't make these things apparent and actionable :)

**Comment by mxilievski** [comment]
seems like we're not the only one affected by this issue https://developer.apple.com/forums/thread/685403. 
But as apple rep "eskimo" says, there is still no bug reported by anyone. In order to report a bug in apple besides an explanation we have to provide a "test" project that will be able to reproduce the problem. 

Is there any iOS dev here that can submit a bug report to apple? 

For now as @zacwest mentioned, the only possible solutions are:
- replacing web socket implementation (too much work, not worth the effort).
- FE guys exposing a function that can be called from iOS so that the web socket connection can be controlled by the iOS app. (By controlled I mean being reset on each app start).

**Comment by Stooovie** [comment]
I'd be even content with a banner that says "connection lost"... At least an interim solution.

**Comment by mxilievski** [comment]
@Stooovie that's the problem, we don't know when the connection is lost, if we do we can easily provide a solution.

**Comment by gieljnssns** [comment]
@zacwest 
I've installed iOS 15.2 beta and this doesn't solve the issue for me. 
I'm using the latest app beta, ha 2021.12.0b1.

**Comment by Stooovie** [comment]
Didn't happen to me in last two days with the Testflight version of the HA app.

**Comment by gieljnssns** [comment]
Do you have background refresh on?
![Uploading BB114EC8-7BE8-4017-9156-134849784EE6.png…]()

**Comment by Stooovie** [comment]
Yes I do. I re-enable it after having it off failed to fix the issue.

**Comment by gieljnssns** [comment]
I've turned it on now. I had it disabled for years.

**Comment by michalk-k** [comment]
but background refresh is located in "location" section of app config. How does it relate to the issue? The problem appears even without location change

**Comment by tenallero** [comment]
Testing latest beta (2021.312) with Testflight.
iOS 15.1.1 (not 15.2 beta)
Still having the same issue.
I will give it more time to observe the behaviour.

**Comment by Stooovie** [comment]
Still hasn't happened once, it's five days now. I'm wracking my brains what could have fixed (or seemingly fixed) the issue on my system. I had it for months (probably since IOS 15 betas).

**Comment by mxilievski** [comment]
@zacwest nice workaround:). Tnx so much for the fix, you’re the best.
Will test once the build is up on testflight.

**Comment by mxilievski** [comment]
@zacwest I've just tested the fix and it works partially. 

If a network change occurs when the app is first started the fix is not working. It only works if the network change occurs once the app is minimised once and then returned to foreground. 

Reproduction steps: 
1. Kill the app from background 
2. Start the app
3. Toggle wifi 
4. Go back to app, nothing works (since you don't have the fix, the 5s timer) 
5. Minimise app for 5 seconds then return to foreground, the fix is still not working.

**Comment by tenallero** [comment]
Testing 2021.315
The firsts tests seem to improve. Short time (minutes) in background ... when back to foreground it refresh correctly. 
But, after a long time in background (hours), when it returns to foreground it does not reactivate correctly. A manual refresh is required.

**Comment by zacwest** [comment]
Found a bug in the initial pass - the server version isn't being updated, so the workaround doesn't work (unless you add the server on 2021.12.0b6 or later).

**Comment by tenallero** [comment]
No
2021.11

**Comment by mxilievski** [comment]
@zacwest im on 2021.12. Still what i wrote above is an issue. When app is initially started and network change occurs while App is still in foreground the fix doesn’t work.

**Comment by tenallero** [comment]
Updated server to 2021.12
iOS frontend latest version using TestFlight

Still the same problem.

**Comment by zacwest** [comment]
Looks like the first pass on the frontend side of this issue doesn't work.

**Comment by tenallero** [comment]
Updated server to 2021.12.1
Updated iOs (iPhone) to 15.2

Still the same problem.

I have noticed that the more applications are open in memory ... the sooner iOS companion websockets are lost.
If iOS Companion is the only app in memory ... the websockets seem to last longer.
But, I can't provide any verifiable metrics. Sorry.

**Comment by Stooovie** [comment]
Yeah, it's back :-/ even with everything updated and using HA app from Testflight.

**Comment by deluxestyle** [comment]
> Updated server to 2021.12.1 Updated iOs (iPhone) to 15.2
> 
> Still the same problem.
> 
> I have noticed that the more applications are open in memory ... the sooner iOS companion websockets are lost. If iOS Companion is the only app in memory ... the websockets seem to last longer. But, I can't provide any verifiable metrics. Sorry.

I have the same feeling, but also not able to prove it

**Comment by tenallero** [comment]
I think we are not alone.

https://bugs.webkit.org/show_bug.cgi?id=228296
https://stackoverflow.com/questions/68466378/ios-15-websocket-inside-wkwebview-issue
https://developer.apple.com/forums/thread/685403?login=true
https://docs.microsoft.com/en-us/answers/questions/564726/ios-15-safari-set-nsurlsession-websocket-on.html
https://groups.google.com/g/jssip/c/Lw0-EIxEOv8?pli=1
https://githubmemory.com/repo/AirenSoft/OvenMediaEngine/issues/517

**Comment by Mariusthvdb** [comment]
Seems worse than before using Ha 2022.2.0.dev20211225 so much it even needs a true reload ( kill app because window won't load at all)

**Comment by Stooovie** [comment]
Yes, much worse. I usually have to kill the app too.

**Comment by zacwest** [comment]
Our attempt at fixing this in core-2021.12.4 is causing the page to die occasionally like this. Pulling to refresh should still be possible when it happens; hopefully in the new year we can do another around on this fix.

**Comment by Stooovie** [comment]
Usually now (HA 2021.12.5, app 2021.327 from Testflight, iOS 15.2) when I get back to the app, the window is completely empty (which is new, this never happened) - just to clarify.

**Comment by zacwest** [comment]
Yeah, the totally empty thing is the new problematic behavior.

**Comment by Camatobe** [comment]
Small additional information (hope it helps):
The empty lovelace screen also appears almost all the time on my iOS12 device, so it seems like this issue is not an iOS15 exclusive thing. 

My device is a wall mounted iPad Air (1st gen with the last iOS 12 Version and 2021.12.1 App Version on it), triggered by a notification which loads the app from the background - almost every time to a blank screen instead of a dashboard.

**Comment by zacwest** [comment]
Please update to core-2021.12.6 (released earlier today) - it includes a fix for the blanking screen issue, which hopefully means iOS-2021.12's workaround will help _most_ cases where the connection is silently dead now.

**Comment by Stooovie** [comment]
It's much better but there's a new (small) bug: where I was getting completely blank screen before, now I sometimes get nothing but the top bar (the Lovelace panels row). But any scrolling action brings the content back, no refresh is necessary.

**Comment by deluxestyle** [comment]
On my iPhone 11 with iOS 15.2 is not really better. I have to refresh now every time

**Comment by gieljnssns** [comment]
On an iPhone XS with iOS 15.3 public beta, I must also refresh a lot.

**Comment by tenallero** [comment]
I have updated core to 2021.12.6
Much better now
Thanks

**Comment by deluxestyle** [comment]
somehow I have the feeling it is even now worse on my Windows PC

**Comment by Mariusthvdb** [comment]
yes, I have mixed feelings too.... my Mac desktop browser is acting up like never before. The lockups the app was experiencing are now happening on my desktop ? Never had to 'refresh' the browser before on that device

if happening, the frontend seems to be responding ok, but its not until refresh the commands get applied to the backend devices... need to investigate further to be able to precisely pinpoint the issue though

**Comment by TomBrien** [comment]
Yep I am now also seeing the same in a desktop browser. Actions seem to happen when pressed (for example dismiss a persistent notification) but the frontend doesn't update until refreshed

**Comment by TomBrien** [comment]
Looks like the desktop side is fixed by home-assistant/frontend#11042 see that PR for related frontend issues

**Comment by deluxestyle** [comment]
I have the feeling that since the update to 2021.12.7 it is much better

**Comment by Stooovie** [comment]
Yes, I think it very obviously reconnects more often but that's fine. I'm not getting the inactive state now.

**Comment by blhoward2** [comment]
It seems that since about around the time this was fixed, I now occasionally experience Lovelace loading over and over again. Many others have reported this on Reddit (e.g. https://www.reddit.com/r/homeassistant/comments/snz9g0/every_time_app_loses_focus_causes_lovelace_to/?utm_source=share&utm_medium=ios_app&utm_name=iossmf). Has anyone else experienced this? Is it a side effect of this fix or a new bug?

**Comment by zacwest** [comment]
Can you share your internal and external URLs? It's unlikely to be this workaround, though possible - if it is, it may require looking at full device logs which you can [drop here](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) and I can take a look; export them from App Configuration > Debugging.

**Comment by blhoward2** [comment]
I’m using Nabu Casa so it’s using the generated address. I’ll grab a log the next time it does it. It’s not every time. I’ll also ask the other guy that started the Reddit thread.

**Comment by melyux** [comment]
This is still happening in 2022.2. Makes the HA app unusable for actually controlling anything unless you have 30 seconds to kill. I'll try on 2022.3.

**Comment by Stooovie** [comment]
@melyux that's kinda weird, I haven't had that happen for months now, on both desktop (Safari and Edge) and the iOS app... For me the HA app version from Testflight (essentially a public beta) fixed it months ago but even the release version is fine now.

**Comment by Camatobe** [comment]
Some report about the unresponsive app are also in this already closed issue (latest comments) https://github.com/home-assistant/iOS/issues/2008 

Got the hanging splash screen on a regular bases on my older iOS 12 ipad Air. Details in the issue I linked.

**Comment by texasmouse** [comment]
> This is still happening in 2022.2. Makes the HA app unusable for actually controlling anything unless you have 30 seconds to kill. I'll try on 2022.3.

+1.  Having the same problem.

I have been following https://community.home-assistant.io/t/ios-15-beta-and-public-release-safari-companion-app-freezing/323755/55, hoping to see any community input.

**Comment by popy2k14** [comment]
Same issue on Android.
App is just blank after reopening and has to killed.
It happens very often (sometimes minutes).

Please fix this issue!
It's hanging around for years now.
