### ISSUE TITLE
Can't pair Matter device (works on HomeKit)

### ISSUE THREAD

**Issue by c10l** [home-assistant/iOS#2574]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro
Software Version: 17.3
App version: 2024.1 (2024.535)

**Home Assistant Core Version**

2024.1.6

**Describe the bug**

Initial pairing of Matter device fails.

The same device pairs fine via Apple Home, everything else being the same.

This is a Meross MSS315 Matter over WiFi smart plug.

**To Reproduce**

Plug device in, factory reset by holding power button for 5-10s.
Open Home Assistant companion app, go to Settings -> Devices & Services
Press `+ Add Integration`
Select `Add Matter Device`
Scan QR code on device
Press `Add to "Home Assistant"`
Wait until it fails

The flow on Apple Home is similar, though the button reads `Add to "Home"` and it actually works.

**Expected behavior**

Pairing works and device is added to Home Assistant.

**Screenshots**

![73619C9E-292D-4B8D-B69F-685A1D950339_1_102_o](https://github.com/home-assistant/iOS/assets/399431/de3f0fe5-4ea2-4a29-8212-c5ca76d4d4ad)
![818133EC-FDC2-4B53-8AA2-9C17FBA8F1DC_1_102_o](https://github.com/home-assistant/iOS/assets/399431/db1c472f-cafe-461e-99f1-2990682aaa2a)
![6E875A41-3FBE-4D9A-9DDE-0D3FA64A9BC4_1_102_o](https://github.com/home-assistant/iOS/assets/399431/76f36728-d822-4622-862b-0688efac9215)
![A89C2302-D3A7-424F-A956-91865D238597_1_102_o](https://github.com/home-assistant/iOS/assets/399431/275f54b4-5edc-4ce2-87de-fa68871f1433)

**Additional context**

The only relevant log I found after exporting the app's logs was this:

```
[Error] [com.apple.root.user-initiated-qos.cooperative] [MatterWrapper.swift:53] commission > Matter pairing failed: Error Domain=com.apple.MatterSupport Code=1 "(null)"
```

There are no logs on the Matter Server add-on outside of the ones that happen when the server is brought up.

The device doesn't even get to the point where it tries to connect to the WiFi. This was verified by tailing `hostapd` logs on the access point / router.

**Comment by bgoncal** [comment]
Are you still experiencing this?

**Comment by c10l** [comment]
I am, yes. Tried it again last week. Happy to do any troubleshooting if someone smarter than me can give me pointers!

**Comment by bgoncal** [comment]
Please, reset the device, try again then after it fails export your companion app logs and upload it here: https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by mikeacar** [comment]
I am also having this issue. What lines should I grep out of the companion app logs?

**Comment by bgoncal** [comment]
@mikeacar Usually the file that has "matter" on the name is enough, but ideally you would share the whole logs exported by the App.

**Comment by mikeacar** [comment]
I filled in the Google form linked above.

As I mentioned in the form, the device I'm having problems with is Thread, not WiFi, so maybe this issue will turn out to be unrelated, since I see the original post was for a WiFi power outlet. There's one other working Thread device on my network, an Aqara Motion and Light Sensor P2. It's within less than a meter of the smart switch and is connected to my HA Yellow.

**Comment by bgoncal** [comment]
@mikeacar I quickly checked it and apparently you are in a dead state that I have seen before but no solution was found for it yet, it's not exactly an app problem but it's something that got out of sync in your thread network + credentials (current assumption.)

Do you have another thread network that you could make the preferred one and try to comission the device again? This would confirm this theory

**Comment by mikeacar** [comment]
I don't, but since I have only one other Thread device, I could try removing the existing network and creating a new one. Would that help?

**Comment by matthewprenger** [comment]
I'm seeing the same issue trying to add an Inovelli white series dimmer switch. I was originally able to add it to HomeKit without issue, but after factory resetting I'm not able to add it to Home Assistant. Logs uploaded to the form linked above.

**Comment by bgoncal** [comment]
@mikeacar if you don't mind, please do it

**Comment by mikeacar** [comment]
Should I use these instructions?

https://community.home-assistant.io/t/remove-thread-network/798171/8

**Comment by mikeacar** [comment]
I removed all the Matter devices from the Matter server, deleted the Matter and Thread integrations, and uninstalled the Matter Add-on and all its data, and the OTBR add-on (though I forgot to delete all its data).
Then I re-added the OTBR add on and the Matter add-on, and added both integrations. In the Thread integration, I went to Preferred Network, which shows only my HA border router, and selected "Use for Android + iOS credentials".

I tried adding the Thread Aqara motion sensor, but that failed. I also tried adding a WiZ WiFi lightbulb, and that also fails, with the message that I might need to reset the device before I can add it. Adding the Thread Eve Smart Light Switch fails too I was able to add my Kasa WiFi light switches. The error from the log is what we've seen before:

```
2025-07-09 21:54:04.404 [Error] [com.apple.root.user-initiated-qos.cooperative] [MatterWrapper.swift:72] commission > Matter pairing failed: Error Domain=com.apple.MatterSupport Code=1 "(null)"
2025-07-09 21:54:48.370 [Error] [com.apple.root.user-initiated-qos.cooperative] [MatterWrapper.swift:72] commission > Matter pairing failed: Error Domain=com.apple.MatterSupport Code=1 "(null)"
2025-07-09 21:55:22.023 [Error] [com.apple.root.user-initiated-qos.cooperative] [MatterWrapper.swift:72] commission > Matter pairing failed: Error Domain=com.apple.MatterSupport Code=1 "(null)"
```

The interesting thing is in the companion app > Settings > Companion app > Debugging > Thread, I have two sets of Thread credentials. I can delete the new set, but I can't delete the old set: I swipe left, click delete, click "Yes", allow Home Assistant to access my home network, and the creds are still in the keychain.

At one point, after trying to set up a Thread device, I got a popup that said it couldn't save Thread credentials, because no Thread network matching the credentials was found (I should have taken a screenshot, sorry about that).

-- Mike

**Comment by bgoncal** [comment]
Ok, so this last information is very important, if it can't save the credentials in your iPhone it is normally because the network is unreachable at that moment or the credentials are wrong.

How far is your iPhone to the thread antenna?

Also, do you have IPV6 enabled in your router?

**Comment by mikeacar** [comment]
My house is pretty small, and I've tried from a few different places in the house. But at one point I was standing less than a meter from the HA Yellow, with nothing in between, while trying to pair the Aqara sensor; it failed.

So I think it's more likely wrong credentials than the network being unreachable.

The router is an Ubiquiti Dream Machine. It doesn't have IPv6 set up, but HAOS does have have IPv6 enabled, set to "automatic". It has two addresses. The zeroconf network browser shows many IPv6 addresses in _matter._tcp.local, along with a couple more for devices in _matterc._udp.local.

So I infer that the Matter devices are setting up their own IPv6 network, as they're supposed to do.

There are three different fabric prefixes among the _matter._tcp.local devices, btw. Not sure if that matters.

Ubiquiti's "multicast enhancement" is disabled; I've read that can cause problems for Matter.

My iPhone has both IPv4 and IPv6 addresses. The network is flat - no VLANs.

-- Mike

**Comment by bgoncal** [comment]
I'll share your case with a co-worker that can help troubleshooting this, I'll get back when I have more info

**Comment by mikeacar** [comment]
Let me also refer to https://github.com/home-assistant/addons/issues/4071, which describes some other Thread issues I'm having, and includes system information. In short, I'm using an older firmware because RCP 2.4.4.0 does not work on my HA Yellow.

-- Mike

**Comment by agners** [comment]
One thing which confuses me, initially you wrote:

> As I mentioned in the form, the device I'm having problems with is Thread, not WiFi, so maybe this issue will turn out to be unrelated, since I see the original post was for a WiFi power outlet. There's one other working Thread device on my network, an Aqara Motion and Light Sensor P2. I

Was that other working Thread device working from Home Assistant or Apple Home?


Not sure if you are aware, but it is unclear to me if you try to onboard devices the first time or share from an exsting Fabric. In general, Matter allows multi-admin, meaning controlling devices from two fabrics. When resetting a device, it will loose all its fabric information (it will no longer be controllable from any fabric). The devices then are stale in the respective controller (Apple Home or Home Assitant) and need to be deleted manually. Usually, it is better to delete the device in the respective smart home platforms *before* resetting the device itself.

> The interesting thing is in the companion app > Settings > Companion app > Debugging > Thread, I have two sets of Thread credentials. I can delete the new set, but I can't delete the old set: I swipe left, click delete, click "Yes", allow Home Assistant to access my home network, and the creds are still in the keychain.

This is somewhat concerning. I am not sure if this is a iOS problem, maybe iOS thinks that these Thread credentials are still being used? Did you delete all Thread devices from Apple Home as well? If not, maybe try that, then delete these credentials again?


> I also tried adding a WiZ WiFi lightbulb, and that also fails, with the message that I might need to reset the device before I can add it. 

How do you try adding currently? Via multi admin (share in Apple Home) or did you reset the device and tried adding from scratch?

**Comment by A-vesalius** [comment]
From my system; Apple home, Home Assistant ZBT-1, and recently added an aqara M3 hub. 

Also have 2 sets of credentials in the iOS HA companion app > Settings > Companion app > Debugging > Thread.

Can only add Matter devices to Apple home first. Either as a first try or after a device reset. 

Can only add to HA or aqara M3 via multi admin after onboarding with Apple Home first. Can not onboard/add a new unused device or a device after reset to either.

**Comment by mikeacar** [comment]
> One thing which confuses me, initially you wrote:
> 
> > As I mentioned in the form, the device I'm having problems with is Thread, not WiFi, so maybe this issue will turn out to be unrelated, since I see the original post was for a WiFi power outlet. There's one other working Thread device on my network, an Aqara Motion and Light Sensor P2. I
> 
> Was that other working Thread device working from Home Assistant or Apple Home?

I have only Home Assistant, not Apple Home.

I realize that's somewhat confusing, given the subject of this issue. Sorry about that.

> Not sure if you are aware, but it is unclear to me if you try to onboard devices the first time or share from an exsting Fabric.

I'm trying to onboard them for the first time (or after reset), not share from a Fabric.

> > The interesting thing is in the companion app > Settings > Companion app > Debugging > Thread, I have two sets of Thread credentials. I can delete the new set, but I can't delete the old set: I swipe left, click delete, click "Yes", allow Home Assistant to access my home network, and the creds are still in the keychain.
> 
> This is somewhat concerning. I am not sure if this is a iOS problem, maybe iOS thinks that these Thread credentials are still being used? Did you delete all Thread devices from Apple Home as well? If not, maybe try that, then delete these credentials again?

Sorry for the confusion; HA is the only hub I have.

> > I also tried adding a WiZ WiFi lightbulb, and that also fails, with the message that I might need to reset the device before I can add it.
> 
> How do you try adding currently? Via multi admin (share in Apple Home) or did you reset the device and tried adding from scratch?

I reset and tried adding from scratch.

-- Mike

**Comment by gunnjr** [comment]
I am experiencing the same issue.  I'll be honest, much of this discussion is over my head (at least until I have the time to learn this subject more deeply).  That said, I'll add a datapoint on my experience that I don't think others have shared yet (unless I missed it.)...

Like others, I can add the device to my thread network via Apple Home.  After doing so, I can successfully add the device to HA by sharing from Apple 'fabric' (share device from Apple Home, get code, add device via HA companion app by selecting "Yes. It's already in use."-->Apple Home-->enter code provided by Apple home).  After adding device thusly, the device appears to function correctly as a Matter over Thread device within Home Assistant (as if it had been originally added as new device from companion app).

ENVIRONMENT
HA System: HAOS on intel NUC
Thread Network: ZBT-1/OTBR
Network:  Unifi Router with multiple VLANS/subnets with HA and companion app connected to same VLAN/subnet
* NOTE: I have not messed with IPV6 or multicast settings on router for fear of disturbing functional connections of multiple Matter over WiFi devices--all of which originally connected and remain connected as they should

**Comment by mikeacar** [comment]
@agners, any thoughts?

**Comment by stebl27** [comment]
I have the same problem.
If I connect the thread device first with Apple Home then I can add it to Home Assistant afterwards.
But initially paring via HA App is not working. 
Thread credentials are synched and companion app has only one single entry.

**Comment by bgoncal** [comment]
Everyone please reproduce the issue a few times then export your companion app logs and upload here https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by abrisco** [comment]
@bgoncal I sent some logs your way as well

**Comment by bgoncal** [comment]
@abrisco I just requested access to your file

**Comment by bgoncal** [comment]
@abrisco I checked your logs and on the App side it looks all right. It was able to successfully save the credentials in your keychain and it was also able to find and select the correct thread network.

@agners this is looking very much like what happened to me a while back and then when I updated to iOS 26 Beta 3 it went away... It could be a coincidence, but possible.

Aqara has also communicated on their public Slack that commissioning devices on iOS 18.4 and 18.5 were very hit and miss lately.

Anyone here also using the iOS 26 beta to confirm or end this theory?

**Comment by abrisco** [comment]
> [@abrisco](https://github.com/abrisco) I checked your logs and on the App side it looks all right. It was able to successfully save the credentials in your keychain and it was also able to find and select the correct thread network.

@bgoncal Interesting. Any indication as to why the pairing failed at the end then? I've been struggling to identify what the core issue is and the symptoms seemed to match this post pretty well.

**Comment by bgoncal** [comment]
Not really, there are not much that Apple shares when it fails

**Comment by LorbusChris** [comment]
Same thing happened to me this week with a HASS Yellow and a Nuki 3rd Gen Pro Smart Lock. I had to onboard the device to my Apple HomePod's thread network first, only then was I able to add it to HASS.

I'll be able to re-run that whole process in 2 weeks (currently traveling). I'll provide logs then if this isn't resolved by then.

**Comment by picklegithub** [comment]
I’m having the same issue on my iPhone 15 an am unable to add thread or matter devices, I just submitted some logs  I also have the same issue on using an Android phone, so it could be some other setting or other issue causing this. 

Model Name: iPhone 15 Pro
Software Version: 18.5
App version: 2025.7.1

Home Assistant Core Version - 2025.7.2

**Comment by bgoncal** [comment]
@picklegithub Your case looks unrelated to the app if you have the issue on both platforms, double check your matter and thread config in Home Assistant.

**Comment by mikeacar** [comment]
Yesterday I was able to pair both of my Thread devices to HA.

The key was to use the Thread integration's "reset border router" option. That created a new network, which I made the preferred network. I transferred the credentials to my phone and was able to add devices.

Curiously, I still don't seem able to delete the keys from my prior network. But I'll give that another try this weekend.

-- Mike

**Comment by jugglerAndrew** [comment]
> [@abrisco](https://github.com/abrisco) I checked your logs and on the App side it looks all right. It was able to successfully save the credentials in your keychain and it was also able to find and select the correct thread network.
> 
> [@agners](https://github.com/agners) this is looking very much like what happened to me a while back and then when I updated to iOS 26 Beta 3 it went away... It could be a coincidence, but possible.
> 
> Aqara has also communicated on their public Slack that commissioning devices on iOS 18.4 and 18.5 were very hit and miss lately.
> 
> Anyone here also using the iOS 26 beta to confirm or end this theory?

@bgoncal  I stumbled upon this thread as I was having similar issues commissioning both Eve and Inovelli devices, even though I already have 10 or so devices (including an Eve) that paired fine just two weeks ago. Anyway, pairing has been unsuccessful on both my iPhone (18.5) and iPad (18.x). Based on your comment, **I updated my iPad to 26 beta... and... pairing worked!** At first it didn't, but then I factory reset each device and then pairing was successful.

**Comment by bgoncal** [comment]
@jugglerAndrew good to hear that, so apparently iOS 26 fixes something around Matter comissioning indeed.

**Comment by Gingervitis-03** [comment]
I was having this exact same issue. I updated to IOS 18.6 and I can now add devices without failing.

**Comment by bgoncal** [comment]
Oh nice, 18.6 was just released right? Then no need to install any beta anymore

**Comment by bgoncal** [comment]
I'll assume the new iOS fixes the issue, but feel free to let me know in case it doesn't and I will reopen this issue.

**Comment by abrisco** [comment]
> [@abrisco](https://github.com/abrisco) I checked your logs and on the App side it looks all right. It was able to successfully save the credentials in your keychain and it was also able to find and select the correct thread network.

I can confirm that after updating my iPhone to iOS 18.6 I was able to pair Matter devices again.

**Comment by glitchykitten** [comment]
FWIW I have been having this same problem and it has been driving me crazy :).  I'll update to 18.6 tonight and try again.  If it's not working after that update I'll come back with more details.

**Comment by glitchykitten** [comment]
Fixed for me with iOS 18.6.

**Comment by kernelkaribou** [comment]
18.6 fixed for me and like @glitchykitten I was losing my mind!

**Comment by mikeacar** [comment]
Posted this on the wrong issue...

Once I have a chance to update, I'll see if I can delete those stuck Thread credentials.
