### ISSUE TITLE
Background updates eventually hang

### ISSUE THREAD

**Issue by lwis** [home-assistant/iOS#2638]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro
Software Version: 17.4
App version: 2024.2

**Home Assistant Core Version**
2024.3.0

**Describe the bug**
Eventually background sensor updates stop happening, running the "Update sensors" shortcut times out. Force closing the app brings everything back to life and the shortcut starts working again.

**To Reproduce**
Have iOS app pushing sensor updates in background for a ~period of time.

**Expected behavior**
App continues to function without repeatedly force closing.

**Comment by lwis** [comment]
It does not update when the app is in the foreground.

I do not have local push enabled, or an internal URL configured.

**Comment by bgoncal** [comment]
Did you observe a pattern for when does it stop reporting? In background I know for sure the sensor updates wont be live without local push enabled but foreground should be working properly.

**Comment by lwis** [comment]
Unfortunately there doesn't seem to be a pattern to it, I have no way to reproduce. Is there anything useful I can capture the next time it happens?

**Comment by bgoncal** [comment]
Can you check the latest testflight beta?  It may have fixed this

**Comment by lwis** [comment]
I'll update to the latest beta and continue to monitor! 🤞🏻

**Comment by lwis** [comment]
Still happening unfortunately, this is what I see when the shortcut fails;

![image](https://github.com/home-assistant/iOS/assets/873275/f35ffd43-d041-4a6c-80ba-d160e914c985)

**Comment by dmulcahey** [comment]
[Home Assistant_2024-03-21_181706.txt](https://github.com/home-assistant/iOS/files/14715171/Home.Assistant_2024-03-21_181706.txt)
[Home Assistant_2024-03-21_192239.txt](https://github.com/home-assistant/iOS/files/14715172/Home.Assistant_2024-03-21_192239.txt)
[Home Assistant_2024-03-21_200921.txt](https://github.com/home-assistant/iOS/files/14715173/Home.Assistant_2024-03-21_200921.txt)
[Home Assistant_2024-03-21_191428.txt](https://github.com/home-assistant/iOS/files/14715174/Home.Assistant_2024-03-21_191428.txt)

**Comment by dmulcahey** [comment]
POSIXErrorCode(rawValue: 28): No space left on device) Is thrown constantly by the app when the WS connection breaks

**Comment by dmulcahey** [comment]
@bgoncal let me know if there is anything you need to assist in debugging this.

**Comment by bgoncal** [comment]
https://stackoverflow.com/questions/67318867/error-domain-nsposixerrordomain-code-28-no-space-left-on-device-userinfo-kcf

This looks related, I'll investigate next week

**Comment by dmulcahey** [comment]
RC still has the issue. I’ll also note that when this happens and you open the app after it has been in the background it doesn’t connect to HA at all. It fails and HA logs the following:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:461
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: March 24, 2024 at 6:32:56 PM (6 occurrences)
Last logged: 7:21:09 AM

[281473247231552] from 192.168.1.68 (Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.603; iOS 17.4.1)): Disconnected: Did not receive auth message within 10 seconds
[281472302263104] from fe80::1460:ed53:6ed7:34ed (Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.603; iOS 17.4.1)): Disconnected: Did not receive auth message within 10 seconds
[281472222859200] from 192.168.1.68 (Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.603; iOS 17.4.1)): Disconnected: Did not receive auth message within 10 seconds
[281471861314368] from fe80::1460:ed53:6ed7:34ed (Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.608; iOS 17.4.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds
[281471753716160] from fe80::1460:ed53:6ed7:34ed (Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.608; iOS 17.4.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds
```

hard closing the app and reopening it resolves the issue. I have been running test flight versions since they started getting published again and this just started with this cycle of work: after CarPlay release version so maybe 2 or 3 test flight pushes back.

**Comment by dmulcahey** [comment]
I just thought of something else. The timing could possibly coincide with the release of iOS 17.4

**Comment by bgoncal** [comment]
Can you consistently reproduce the issue in some way? Like rebooting HA with the App open for example. I would like to have the same issue happening on my device to investigate it better, for now I couldn't reproduce

**Comment by lwis** [comment]
Having a Shortcut automation which fires on power connect and disconnect to "Update Sensors" in the background is the way this manifests most often for me.

**Comment by bgoncal** [comment]
@dmulcahey Im checking your logs, when they happened were you somewhere http://192.168.1.78:8123 was accessible? (your home probably) or were you using external URL?

**Comment by dmulcahey** [comment]
I work from home and am generally here. I just opened the app from the background again. Last open was around the time of my last reply and it happened again. I’ll get new logs for you in a few. Can you give me somewhere to send an iCloud link so I can get you the full bundle from the app?

**Comment by bgoncal** [comment]
Are you in discord? You can ping me there @bgoncal2

**Comment by bgoncal** [comment]
Im preparing a testflight build with a possible fix , when you see 2024.612 in testflight you can test it

**Comment by dmulcahey** [comment]
> Im preparing a testflight build with a possible fix , when you see 2024.612 in testflight you can test it

Just saw this update and installed it. Will report back

**Comment by dmulcahey** [comment]
> Im preparing a testflight build with a possible fix , when you see 2024.612 in testflight you can test it

Initial testing looks good. Let’s see how it does overnight

**Comment by dmulcahey** [comment]
Everything is still working. What was the issue?

**Comment by bgoncal** [comment]
I'm still investigating but initially I believe the issue is that StarScream lib we use for websocket interaction creates one URLSession per request, which in a retry loop goes over iOS limits. I believe this wasn't happening in some updates ago because we were still supporting iOS 12 at that time and this limit was not applied.
I created a PR to starscream https://github.com/daltoniam/Starscream/pull/1011

**Comment by bgoncal** [comment]
Heads up that this fix is not on our main branch yet, so if you see new builds coming in testflight, they may revert this fix

**Comment by bgoncal** [comment]
@lwis can you also check if this works for you?

**Comment by lwis** [comment]
Updated this morning, so maybe too early to tell, but I've not run into any issues yet.

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed, I'm closing this issue for now and planning the next release to include the fix

**Comment by lwis** [comment]
Bad news; it happened again this morning. I'm unable to run the shortcut directly at all. The app is fully functional. Closing the app allows the shortcut to run again.

I grabbed logs before closing the app.

![image](https://github.com/home-assistant/iOS/assets/873275/d13891ea-ff55-4b5c-827d-9c2432f8833b)

![image](https://github.com/home-assistant/iOS/assets/873275/dd586be8-0ad1-4e01-b958-79c57ab6d8e1)

2024.624

**Comment by lwis** [comment]
This is still happening, please let me know if there's any way I can help!

**Comment by bgoncal** [comment]
Im doing some clean up around shortcuts, widgets and intents in general, I'll let you know when you can test it again

**Comment by Buddinski88** [comment]
@bgoncal I have the same behaviour with the current beta 2024.696 and iOS 17.5.1. Has there been any progress in fixing the bug?

**Comment by bgoncal** [comment]
Do you see anything in your logs? Like 503 error?
Also do you have any secondary Server that is not reachable when this error occurs?

**Comment by Buddinski88** [comment]
> Do you see anything in your logs? Like 503 error? Also do you have any secondary Server that is not reachable when this error occurs?

Interesting. I've just done some research. If I connect the app directly locally via IP, the update works. So it has something to do with the external connection, which I set up via Cloudflare Tunnel.
When I look at the logs, I see various errors. I've restarted the plugin and so far it's working again. I'll get back to you as soon as the error occurs again.
But it definitely has something to do with the connection via Cloudflare Tunnel.

**Comment by bgoncal** [comment]
> This is still happening, please let me know if there's any way I can help!

Do you have more than 1 server? Both has external access enabled? Do you see webhook error 503 in your logs?

**Comment by alams154** [comment]
I’m experiencing the same issue where the update shortcut only works locally.  The HA app is able to update the sensors periodically while it is completely closed and does an immediate push after opening the HA app.

I have 2 servers and only one server has external access enabled via Cloudflare Tunnel.  I don’t see 503 in my logs but I do see POSIX Error 57.

I’ll try to upload my logs sometime soon if that will help.

**Comment by alams154** [comment]
Some more information about my setup:
Using cloudflared as tunnel to server
Using traefik as reverse proxy to home assistant
Related traefik router rules:
```
homeassistant-rtr:
  service: homeassistant-svc
  rule: "Host(`homeassistant.sollab.app`)"
  entryPoints: https
  tls: true
  middlewares: authelia@docker
homeassistant-api-rtr:
  service: homeassistant-svc
  rule: 
    Host(`homeassistant.sollab.app`) && 
    (PathPrefix(`/api/google_assistant`) || 
      PathPrefix(`/api/webhook`) || 
      PathPrefix(`/api/websocket`) || 
      PathPrefix(`/auth/authorize`) || 
      PathPrefix(`/auth/token`) || 
      (ClientIP(`10.0.0.0/24`) && !ClientIP(`10.0.0.130`))
    )
  entryPoints: https
  tls: true
```

Here are my logs
[Home Assistant.txt](https://github.com/user-attachments/files/16737494/Home.Assistant.txt)
[Home Assistant_2024-08-22_064119.txt](https://github.com/user-attachments/files/16737495/Home.Assistant_2024-08-22_064119.txt)
[Home Assistant_2024-08-23_064242.txt](https://github.com/user-attachments/files/16737496/Home.Assistant_2024-08-23_064242.txt)
[Home Assistant_2024-08-24_101522.txt](https://github.com/user-attachments/files/16737497/Home.Assistant_2024-08-24_101522.txt)
[HomeAssistant-Extensions-PushProvider.txt](https://github.com/user-attachments/files/16737498/HomeAssistant-Extensions-PushProvider.txt)

**Comment by SneakieGargamel** [comment]
I am also having the same problem, did you get it solved?

**Comment by alams154** [comment]
Finally found a solution.  Switching to the "Reload widgets" action in Shortcuts fixes the issue.  This action still updates all the sensors and doesn't have the 1307 timeout error in the "Update sensors" action and it's much faster.

See this thread for more info https://community.home-assistant.io/t/shortcuts-to-update-sensors/777904/8.
