### ISSUE TITLE
Local push disabled on internal URL

### ISSUE THREAD

**Issue by erkr** [home-assistant/iOS#3392]
**iOS device model, version and app version**

Model Name: iPhone 14
Software Version: 18.1
App version: 2025.2 (2025.1117)

**Home Assistant Core Version**
2025.1.4

**Describe the bug**
Local push and SSID's are enabled in the settings for internal URL.
But I see a status of being connected internally, where local push remains disabled

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/550507e5-659b-4382-9b34-f2e61d6bf4cf)

**Additional context**

**Comment by erkr** [comment]
Issue still persists on latest version 2025.1175

**Comment by bgoncal** [comment]
Do you have location permission "Always" allowed? 

Also please try rebooting your phone

**Comment by erkr** [comment]
@bgoncal 
Location Always is allowed and my phone was rebooted several times since reporting the issue. 
Not sure if the status reported in the settings is wrong, or local push is indeed disabled.
Is the a way to verify that?
Best Eric

**Comment by bgoncal** [comment]
When I saw your report I tested it in several devices at my place in 3 different networks and I couldn't reproduce, is it possible that you have the SSID incorrectly there? Perhaps one trailing space or something like this.
If you also have a way to try in a different network, it would be interesting to debug.

Meanwhile after you try that, drop me your companion app logs please https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by erkr** [comment]
Done. SSID's are correct (App also mentions it is using the internal URL). Did another reboot of the phone before uploading the logs. Hope it helps

**Comment by erkr** [comment]
@bgoncal where the log files of any use? Can I do more?

**Comment by bgoncal** [comment]
Sorry for the late reply, I was on vacations, I couldn't find the root cause yet by checking the logs, it's on my todo list to investigate this

**Comment by erkr** [comment]
Update - I noticed this menu in the companion app:

![image](https://github.com/user-attachments/assets/d35bad25-54f1-466b-9340-45ecb286acee)

I received several notifications today. So does that imply local notifications are enabled, but it's just the state in the menu that suggests not?! Or do I misunderstand?!

**Comment by Gazoonky** [comment]
This is still broken, however I have discovered that iOS updates (and/or perhaps app updates) turn local push off in the companion app settings.
Local push can be turned on again by clicking on "internal URL" in the server settings of the companion app settings in HA, then restarting the HA app.

**Comment by erkr** [comment]
@Gazoonky 
Thanks that works. I missed the need to restart the app after enabling local push on the internal URL. 
I now have this: 
![image](https://github.com/user-attachments/assets/eaf73b03-1acb-402f-a8d0-b111a689da6c)
No clue what the number (0) means?! Update: the number of notifications send

**Comment by erkr** [comment]
@bgoncal 
Based on the new insights, it seems we have two issues with local push:
- setting local push gets disabled after an update (iOS and / or app?!). I recently updated both. So can't confirm which of these updates disabled it
- enabling local push requires an app restart to become active

**Comment by bgoncal** [comment]
> setting local push gets disabled after an update (iOS and / or app?!). I recently updated both. So can't confirm which of these updates disabled it

Correct, due to high battery consumption and the average user not even knowing what local push is, it was decided to turn it off by default, so a side effect of one of the latets updates was having it turned off.

> enabling local push requires an app restart to become active

The root cause of this is still unknown to me, I was also able to make it work again by turning off wifi waiting a bit and turning it on again.

**Comment by cvincent** [comment]
I'll add that, for me, the only reason I know what local push is is that a couple months ago it became the _only_ way I get push notifications from HA. Non-local push notifications had just stopped working, and when I looked into it, I discovered local push and that it worked. And then when local push would stop working too, I would notice each time.

**Comment by erkr** [comment]
Still aan issue. Cumbersome to re-enable the setting after each app update

**Comment by bgoncal** [comment]
There is a possible fix that I merged today, keep an eye on TestFlight. It won't be released to the App Store this year anymore though.

**Comment by erkr** [comment]
Installed. Will report back with the next update

**Comment by Gazoonky** [comment]
This is still happening.

**Comment by erkr** [comment]
Just updated to 2026.1705, and for me this time the setting persisted the update 👌

**Comment by Gazoonky** [comment]
2026.1705?

What is that, I don't see any new updates? Are you on beta?

**Comment by erkr** [comment]
Yes that is a beta via test flight

**Comment by erkr** [comment]
For me it's fixed. Setting remained perseved with the lasted beta updates 👍
